### PR TITLE
133

### PR DESCRIPTION
**Pull request by danse**

### CODE REVIEW

**Comment by grillazz** [comment]
@danse as per fact that we did work twice - i can't automatically merge this pull request b/c we have conflicts already. Could you please align this pull request to present version of KC repo please. Thanks, Jakub

**Comment by danse** [comment]
@grillazz i fixed the conflicts and i updated the migrations. i could not test this because of the login problems

**Comment by danse** [comment]
okay i tested it and it works, albeit the style is slightly broken, as i said

**Comment by grillazz** [comment]
do you want me to check CSS ?

**Comment by grillazz** [comment]
looks i need to review CSS b/c page is now rendering incorrectly

**Comment by danse** [comment]
@grillazz yes, i broke the style with this, at least i broke it on the overview page. I thought that it would have been easier to see the actual conflicts and fix them

**Pull request merged**
